### ISSUE TITLE
ts-nodeのインストールが必要でした

### ISSUE THREAD

**Issue by desmowater** [unchain-tech/ETH-DAO#7]
Section 2　Lesson 2「NFTをデプロイしよう」の「SDK の初期化を実行する」で
`yarn node --loader ts-node/esm src/scripts/1-initialize-sdk.ts`を実行したところ、以下のエラーが出ました。

`Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ts-node' imported from C:\Users\hiros\LocalRepository\UNCHAIN\ETH-DAO\`

エラーメッセージに従ってts-nodeをインストールしたところ、エラーが解消されました。
`npm install --save typescript ts-node`

原因はよく分りません。ちなみにnode.jsはv16.14.0です。

**Comment by yk-saito** [comment]
ご報告ありがとうございます🙇

4de168e6dc6032391a12200283c82efa00e27410 にて、スターターにあらかじめ`ts-node`が含まれるよう対応いたしました。
